version: "3.9"

services:
  shopping-cart:
    build: .

    container_name: shopping-cart

    ports:
      - "4321:4321"

    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 4321

    restart: unless-stopped
